import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../../src/app/components/Header/page";
import React from "react";
import CartProvider from "../app/components/Providers/CartProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <section className="relative">
            <div className="sticky top-4 z-50">
              <Header />
            </div>
            <div className="h-[30vh]" />
          </section>
          <main className="-mt-40">
            {children}
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
